
version: '3.7'

services:
    dev:
        image: mcr.microsoft.com/vscode/devcontainers/javascript-node:14
        env_file:
            - ./db.env
        ports:
            - 3000:3000
            - 3001:3001
        volumes:
            - ..:/workspace
        command: sleep infinity
        user: node
    db:
        image: "postgres:13.1"
        restart: always
        env_file:
            - ./db.env
        ports:
            - 5432:5432
        volumes:
            - database-data:/var/lib/postgresql/data
volumes:
    database-data: